bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_xml_file: "follow_point.xml"

    plugin_lib_names: ["nav2_compute_path_to_pose_action_bt_node",
    "nav2_follow_path_action_bt_node",
    "nav2_back_up_action_bt_node",
    "nav2_wait_action_bt_node",
    "nav2_clear_costmap_service_bt_node",
    "nav2_is_stuck_condition_bt_node",
    "nav2_goal_reached_condition_bt_node",
    "nav2_goal_updated_condition_bt_node",
    "nav2_initial_pose_received_condition_bt_node",
    "nav2_reinitialize_global_localization_service_bt_node",
    "nav2_rate_controller_bt_node",
    "nav2_distance_controller_bt_node",
    "nav2_speed_controller_bt_node",
    "nav2_truncate_path_action_bt_node",
    "nav2_goal_updater_node_bt_node",
    "nav2_recovery_node_bt_node",
    "nav2_pipeline_sequence_bt_node",
    "nav2_round_robin_node_bt_node",
    "nav2_transform_available_condition_bt_node",
    "nav2_time_expired_condition_bt_node",
    "nav2_distance_traveled_condition_bt_node"]

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

# Local Costmap
local_costmap:
  ros__parameters:
    footprint: [0.6775, 0.4325, 0.6775, -0.4325, -0.6775, -0.4325, -0.6775, 0.4325]

    update_frequency: 5.0
    publish_frequency: 2.0
  
    global_frame: "map"
    robot_base_frame: "base_link"
    
    rolling_window: True
    always_send_full_costmap: False
    width: 3
    height: 3
    resolution: 0.05

    plugins: ["static_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      enabled: True
      map_topic: "/map"
      map_subscribe_transient_local: True
      subscribe_to_updates: True
      transform_tolerance: 0.1

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: True
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
    
    #TODO: add back
    # obstacle_layer:
    #   plugin: "nav2_costmap_2d::ObstacleLayer"
    #   enabled: True
    #   observation_sources: scan
    #   scan:
    #     topic: /scan
    #     max_obstacle_height: 2.0
    #     clearing: True
    #     marking: True
    #     data_type: "LaserScan"

local_costmap_client:
  ros__parameters:
    use_sim_time: True
  
local_costmap_rclcpp_node:
  ros__parameters:
    use_sim_time: True

# Global Costmap
global_costmap:
  ros__parameters:
    footprint: [0.6775, 0.4325, 0.6775, -0.4325, -0.6775, -0.4325, -0.6775, 0.4325]

    update_frequency: 1.0
    publish_frequency: 1.0

    global_frame: "map"
    robot_base_frame: "base_link"

    resolution: 0.05
    always_send_full_costmap: False
    rolling_window: True
    width: 100  
    height: 100

    plugins: ["static_layer", "inflation_layer"]
    #TODO: add back
    # obstacle_layer:
    #   plugin: "nav2_costmap_2d::ObstacleLayer"
    #   enabled: True
    #   observation_sources: scan
    #   scan:
    #     topic: /scan
    #     max_obstacle_height: 2.0
    #     clearing: True
    #     marking: True
    #     data_type: "LaserScan"
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      enabled: True
      map_topic: "/map"
      map_subscribe_transient_local: True
      subscribe_to_updates: True
      transform_tolerance: 0.1

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: True
      cost_scaling_factor: 3.0
      inflation_radius: 0.55


global_costmap_client:
  ros__parameters:
    use_sim_time: True

global_costmap_rclcpp_node:
  ros__parameters:
    use_sim_time: True

map_server:
  ros__parameters:
    topic_name: "map"
    frame_id: "map"
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["backup", "wait"]
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: True
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: True



