transform_tolerance: 0.1  # ROS2 transform_tolerance: 1.0
gui_publish_rate: 10.0

global_frame_id: "map"
odom_frame_id: "odom"
base_frame_id: "base_footprint"

odom_model_type: diff-corrected
odom_alpha1: 0.0098
odom_alpha2: 0.0098
odom_alpha3: 0.0008
odom_alpha4: 0.0008

resample_interval: 1
update_min_a: 0.2
update_min_d: 0.25

max_particles: 2000
min_particles: 500

laser_model_type: likelihood_field
laser_likelihood_max_dist: 2.0
laser_lambda_short: 0.1
laser_sigma_hit: 0.2
laser_z_hit: 0.5
laser_z_max: 0.05
laser_z_rand: 0.5
laser_z_short: 0.05
kld_err: 0.05
kld_z: 0.99
laser_max_beams: 60
recovery_alpha_fast: 0.0
recovery_alpha_slow: 0.0
