amcl:
  ros__parameters:
    use_sim_time: True
    set_initial_pose: true
    always_reset_initial_pose: false
    save_pose_rate: 0.5
    tf_broadcast: true
    transform_tolerance: 1.0

    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    scan_topic: scan
    map_topic: map

    robot_model_type: "differential"
    alpha1: 0.0098
    alpha2: 0.0098
    alpha3: 0.0008
    alpha4: 0.0008

    resample_interval: 1
    update_min_a: 0.2
    update_min_d: 0.25

    max_particles: 2000
    min_particles: 500

    laser_model_type: "likelihood_field"
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_likelihood_max_dist: 2.0
    lambda_short: 0.1
    sigma_hit: 0.2
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    pf_err: 0.05
    pf_z: 0.99
    max_beams: 60
    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True
