localization_generator:
  ros__parameters:

    use_sim_time: True

    # localization parameters
    update_pose_rate: 1.0
    translation_error: 0.1
    rotation_error: 0.1

    # other parameters
    publish_tf_rate: 50.0
    ground_truth_timeout: 0.5
    ground_truth_start_timeout: 5.0
    transform_tolerance: 1.0

    # topic names
    generated_pose_topic: /generated_pose
    ground_truth_pose_topic: /ground_truth_odom

    # frame names
    fixed_frame: map
    odom_frame: odom
    robot_base_frame: base_footprint
