base_local_planner: rl_local_planner/RLLocalPlanner #dwa_local_planner/DWAPlannerROS 
# base_global_planner: navfn/NavfnROS - we use a different global planner, so I commented this line
update_frequency: 10.0
