robots_dataset: ~/ds/performance_modelling/test_datasets/robots

components_configurations_folder: ~/w/ros2_ws/src/local_planning_performance_modelling/config/component_configurations
gazebo_model_path_env_var: [~/w/ros2_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/]
gazebo_plugin_path_env_var: [~/w/ros2_ws/build/gazebo_plugins/]

supervisor_component: local_planning_benchmark_supervisor

components_configuration:
  supervisor: local_planning_benchmark_supervisor/local_planning_benchmark_supervisor.yaml
  nav2_amcl: nav2_amcl/nav2_amcl_1.yaml
  nav2_navigation: nav2_navigation/navigation.yaml
  teb: nav2_navigation/teb.yaml
  dwb: nav2_navigation/dwb.yaml
  navfn: nav2_navigation/navfn.yaml
  smac: nav2_navigation/smac.yaml
  rviz: rviz/nav2_default_view.rviz

combinatorial_parameters: [
  {
    robot_model: [turtlebot3_waffle_performance_modelling],
    local_planner_node: [dwb],
    global_planner_node: [navfn],
    run_index: [0, 1, 2]
  },
]
