#run_index: &id001 [0, 1, 2]
run_index: &id001 [4]

environment_name: &id002 [airlab]
#environment_name: &id002 [7A-2, airlab, fr079, intel, mexico, office_b]

combinatorial_parameters: [
  {
    robot_model: [turtlebot3_waffle_performance_modelling],
    odometry_error: [[0.0, 0.0, 0.0, 0.0]],
    amcl_alpha_factor: [0],
    localization_node: [amcl],
    local_planner_node: [dwa],
    global_planner_node: [global_planner],
    run_index: *id001,
    environment_name: *id002,
  },
  #{
   # robot_model: [turtlebot3_waffle_performance_modelling],
   # odometry_error: [[0.02, 0.0, 0.02, 0.0], [0.05, 0.0, 0.05, 0.0], [0.1, 0.0, 0.1, 0.0]],
   # amcl_alpha_factor: [1.0],
   # localization_node: [amcl],
   # local_planner_node: [dwa],
   # global_planner_node: [global_planner],
   # run_index: *id001,
   # environment_name: *id002,
  #},
]
