run_index: &id001 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
#run_index: &id001 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

environment_name: &id002 [7A-2, airlab, fr079, intel, mexico, office_b]

combinatorial_parameters: [
#  {
#    robot_model: [hunter2],
#    odometry_error: [[0.0, 0.0, 0.0, 0.0]],
#    amcl_alpha_factor: [0],
#    localization_node: [amcl],
#    local_planner_node: [teb],
#    global_planner_node: [smac, navfn],
#    max_steering_angle_deg: [20, 40],
#    run_index: *id001,
#    environment_name: *id002,
#  },
#  {
#    robot_model: [hunter2],
#    odometry_error: [[0.02, 0.0, 0.02, 0.0], [0.05, 0.0, 0.05, 0.0], [0.1, 0.0, 0.1, 0.0]],
#    amcl_alpha_factor: [0.5, 0.75, 1.0, 1.5, 2.0],
#    localization_node: [amcl],
#    local_planner_node: [teb],
#    global_planner_node: [smac, navfn],
#    max_steering_angle_deg: [20, 40],
#    run_index: *id001,
#    environment_name: *id002,
#  },

  {
    robot_model: [turtlebot3_waffle_performance_modelling],
    odometry_error: [[0.0, 0.0, 0.0, 0.0]],
    amcl_alpha_factor: [0],
    localization_node: [amcl],
    local_planner_node: [teb],
#    global_planner_node: [smac, navfn],
    global_planner_node: [navfn],
    max_steering_angle_deg: [90],
#    max_steering_angle_deg: [20, 40, 90],
    run_index: *id001,
    environment_name: *id002,
  },
  {
    robot_model: [turtlebot3_waffle_performance_modelling],
    odometry_error: [[0.02, 0.0, 0.02, 0.0], [0.05, 0.0, 0.05, 0.0], [0.1, 0.0, 0.1, 0.0]],
    amcl_alpha_factor: [1.0],
#    amcl_alpha_factor: [0.5, 0.75, 1.0, 1.5, 2.0],
#    amcl_alpha_factor: [0.5, 1.0, 1.5, 2.0],
    localization_node: [amcl],
    local_planner_node: [teb],
#    global_planner_node: [smac, navfn],
    global_planner_node: [navfn],
    max_steering_angle_deg: [90],
#    max_steering_angle_deg: [20, 40, 90],
    run_index: *id001,
    environment_name: *id002,
  },

  {
    robot_model: [turtlebot3_waffle_performance_modelling],
    odometry_error: [[0.0, 0.0, 0.0, 0.0]],
    amcl_alpha_factor: [0],
    localization_node: [amcl],
    local_planner_node: [dwb],
    global_planner_node: [navfn],
    run_index: *id001,
    environment_name: *id002,
  },
  {
    robot_model: [turtlebot3_waffle_performance_modelling],
    odometry_error: [[0.02, 0.0, 0.02, 0.0], [0.05, 0.0, 0.05, 0.0], [0.1, 0.0, 0.1, 0.0]],
    amcl_alpha_factor: [1.0],
#    amcl_alpha_factor: [0.5, 0.75, 1.0, 1.5, 2.0],
#    amcl_alpha_factor: [0.5, 1.0, 1.5, 2.0],
    localization_node: [amcl],
    local_planner_node: [dwb],
    global_planner_node: [navfn],
    run_index: *id001,
    environment_name: *id002,
  },

  {
    robot_model: [turtlebot3_waffle_performance_modelling],
    odometry_error: [[0.0, 0.0, 0.0, 0.0]],
    amcl_alpha_factor: [0],
    localization_node: [amcl],
    local_planner_node: [rpp],
    fixed_rpp: [True],
    global_planner_node: [navfn],
    run_index: *id001,
    environment_name: *id002,
  },
  {
    robot_model: [turtlebot3_waffle_performance_modelling],
    odometry_error: [[0.02, 0.0, 0.02, 0.0], [0.05, 0.0, 0.05, 0.0], [0.1, 0.0, 0.1, 0.0]],
    amcl_alpha_factor: [1.0],
#    amcl_alpha_factor: [0.5, 0.75, 1.0, 1.5, 2.0],
#    amcl_alpha_factor: [0.5, 1.0, 1.5, 2.0],
    localization_node: [amcl],
#    local_planner_node: [dwb, rpp],
    local_planner_node: [rpp],
    fixed_rpp: [True],
    global_planner_node: [navfn],
    run_index: *id001,
    environment_name: *id002,
  },
]
