robots_dataset: ~/ds/performance_modelling/test_datasets/robots

components_configurations_folder: ~/w/ros2_ws/src/local_planning_performance_modelling/config/component_configurations
gazebo_model_path_env_var: [~/w/ros2_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/]
gazebo_plugin_path_env_var: [~/w/ros2_ws/build/gazebo_plugins/]

supervisor_component: local_planning_benchmark_supervisor

hunter2_wheelbase: 0.65
hunter2_footprint: [[0.87, 0.47], [0.87, -0.47], [-0.20, -0.47], [-0.20, 0.47]]
turtlebot_radius: 0.22

components_configuration:
  supervisor: local_planning_benchmark_supervisor/local_planning_benchmark_supervisor.yaml
  nav2_amcl: nav2_amcl/nav2_amcl_1.yaml
  nav2_navigation: nav2_navigation/navigation.yaml
  behaviour_tree: nav2_navigation/navigate_w_replanning.xml
  rpp: nav2_navigation/rpp.yaml
  teb: nav2_navigation/teb.yaml
  dwb: nav2_navigation/dwb.yaml
  navfn: nav2_navigation/navfn.yaml
  smac: nav2_navigation/smac.yaml
  rviz: rviz/nav2_default_view.rviz

run_index: &id001 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

combinatorial_parameters: [
  {
    robot_model: [hunter2],
    local_planner_node: [teb],
    global_planner_node: [navfn],
    max_steering_angle_deg: [30],
    run_index: *id001,
  },
]
